#!/bin/bash

if [ $# -eq 0 ]; then
    echo ''
    echo 'usage: ./bwres <prototype function name>'
    echo ''
    scripts/wres commands
    echo ''
else
    echo 'Building WRES...'
    ../gradlew installDist &>/dev/null
    echo 'WRES Built, now running...'
    scripts/wres $@
fi
