#!/bin/bash

if [ $# -eq 0 ]; then
    echo ''
    echo 'usage: ./wres <prototype function name>'
    echo ''
    build/install/wres-core/bin/wres-core commands
else
    build/install/wres-core/bin/wres-core $@
fi
