version: '2.2'
services:
    tasker:
        ports:
         - "443:8443"
        image: "8072a61e65a7"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_secrets:/wres_secrets:ro,z
        environment:
         - JAVA_OPTS=-Xms160m -Xmx160m -Dwres.broker=broker -Dwres.env=ti
        mem_limit: 360m
    broker:
        ports:
         - "5671:5671"
         - "15671:15671"
        image: "d878bdf609c1"
        restart: always
        volumes:
         - /mnt/wres_secrets:/wres_secrets:ro,z
    worker:
        image: "75a2dfbab302"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_share:/wres_data:z
         - /mnt/wres_secrets:/wres_secrets:ro,z
        environment:
         - JAVA_OPTS=-Xms1728m -Xmx1728m -Dwres.broker=broker
        mem_limit: 2048m
