version: '2.2'
services:
    tasker:
        ports:
         - "443:8443"
        image: "${DOCKER_REGISTRY}/wres/wres-tasker:20190624-5e838bc"
        restart: always
        depends_on:
         - "broker"
        volumes:
         # For certificates and keys that correspond to them:
         - /mnt/wres_secrets:/wres_secrets:ro
         # To read output data:
         - /mnt/wres_share:/mnt/wres_share
        environment:
         # Make sure to pass through WRES_ENV_SUFFIX to tasker at runtime
         - JAVA_OPTS=-Dwres.broker=broker -Dwres.environment=${WRES_ENV_SUFFIX}
        # Tasker JVM should have 449m max heap specified at launch
        # The total limit includes stack space which depends on Thread count
        mem_limit: 1024m
    broker:
        ports:
         - "5671:5671"
         - "15671:15671"
        image: "${DOCKER_REGISTRY}/wres/wres-broker:20190426-048cdf6"
        restart: always
        volumes:
         # For certificates and keys that correspond to them:
         - /mnt/wres_secrets:/wres_secrets:ro
        environment:
         - RABBITMQ_CONFIG_FILE=rabbitmq${WRES_ENV_SUFFIX}.config
        # rabbitmq.conf should have 180m specified as high watermark
        mem_limit: 360m
    worker:
        image: "${DOCKER_REGISTRY}/wres/wres-worker:20190626-6ca8310"
        restart: always
        depends_on:
         - "broker"
        volumes:
         # For input and output data:
         - /mnt/wres_share:/mnt/wres_share
         # For certificates, keys that correspond to them, and .pgpass:
         - /mnt/wres_secrets:/wres_secrets:ro
        environment:
         - JAVA_OPTS=-Dwres.broker=broker -Djava.io.tmpdir=/mnt/wres_share/evaluations
         - PGPASSFILE=/wres_secrets/.pgpass
         #- INNER_JAVA_OPTS=-Dwres.logLevel=trace
        # Worker JVM should have 32m heap, wres should have 2310m heap
        mem_limit: 2730m
