version: '2.2'
services:
    tasker:
        ports:
         - "443:8443"
        image: "8072a61e65a7"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_secrets:/wres_secrets:ro,z
        environment:
         - JAVA_OPTS=-Dwres.broker=broker -Dwres.env=ti
        # Tasker JVM should have 160m max heap specified at launch
        mem_limit: 360m
    broker:
        ports:
         - "5671:5671"
         - "15671:15671"
        image: "eb866545d771"
        restart: always
        volumes:
         - /mnt/wres_secrets:/wres_secrets:ro,z
        # rabbitmq.conf should have 180m specified as high watermark
        mem_limit: 360m
    worker:
        image: "75a2dfbab302"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_share:/wres_data:z
         - /mnt/wres_secrets:/wres_secrets:ro,z
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
        # Worker JVM should have 32m heap, wres should have 1628m heap
        mem_limit: 2048m
