version: '2.2'
services:
    tasker:
        ports:
         - "443:8443"
        image: "a8d822a4bd84"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_secrets:/wres_secrets:ro,z
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
        # Tasker JVM should have 160m max heap specified at launch
        mem_limit: 360m
    broker:
        ports:
         - "5671:5671"
         - "15671:15671"
        image: "3136d3c05577"
        restart: always
        volumes:
         - /mnt/wres_secrets:/wres_secrets:ro,z
        environment:
         - RABBITMQ_CONFIG_FILE=rabbitmq${WRES_ENV_SUFFIX}.conf
        # rabbitmq.conf should have 180m specified as high watermark
        mem_limit: 360m
    worker:
        image: "826ee6b9f097"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_share:/wres_data:z
         - /mnt/wres_secrets:/wres_secrets:ro,z
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
         - PGPASSFILE=/wres_secrets/.pgpass
        # Worker JVM should have 32m heap, wres should have 1628m heap
        mem_limit: 2048m
