version: '3'
services:
    ***REMOVED***wres:
        ports:
         - "8585:8585"
        image: "84aab85a935f"
        restart: always
    ***REMOVED***wres-broker:
        ports:
         - "4369:4369"
         - "5671:5671"
         - "5672:5672"
         - "25672:25672"
        image: "rabbitmq:3.7.4-alpine"
        restart: always
    ***REMOVED***wres-worker:
        image: "1c442d030069"
        restart: always
