version: '2.2'
services:
    tasker:
        ports:
         - "443:8443"
        image: "${DOCKER_REGISTRY}/wres/wres-tasker:20190802-a734df8"
        restart: always
        depends_on:
         - "broker"
        volumes:
         # For certificates and keys that correspond to them:
         - /mnt/wres_secrets:/wres_secrets:ro
         # To read output data:
         - /mnt/wres_share:/mnt/wres_share
        environment:
         # Make sure to pass through WRES_ENV_SUFFIX to tasker at runtime
         - JAVA_OPTS=-Dwres.broker=broker -Dwres.environment=${WRES_ENV_SUFFIX} -XX:HeapDumpPath=/mnt/wres_share
        # Tasker JVM should have 1795m max heap specified at launch
        # The total limit includes stack space which depends on Thread count
        mem_limit: 2370m
    broker:
        ports:
         - "5671:5671"
         - "15671:15671"
        image: "${DOCKER_REGISTRY}/wres/wres-broker:20190802-a734df8"
        restart: always
        volumes:
         # For certificates and keys that correspond to them:
         - /mnt/wres_secrets:/wres_secrets:ro
        environment:
         - RABBITMQ_CONFIG_FILE=rabbitmq${WRES_ENV_SUFFIX}.config
        # rabbitmq.conf should have 180m specified as high watermark
        mem_limit: 360m
    worker:
        image: "${DOCKER_REGISTRY}/wres/wres-worker:20190802-a734df8"
        restart: always
        depends_on:
         - "broker"
        volumes:
         # For input and output data:
         - /mnt/wres_share:/mnt/wres_share
         # For certificates, keys that correspond to them, and .pgpass:
         - /mnt/wres_secrets:/wres_secrets:ro
        environment:
         - JAVA_OPTS=-Dwres.broker=broker -Djava.io.tmpdir=/mnt/wres_share/evaluations -XX:HeapDumpPath=/mnt/wres_share
         - PGPASSFILE=/wres_secrets/.pgpass
         # Do not auto-liquibase-migrate on each evaluation. This requires an
         # administrator to run the migration(s) during or after deployment.
         # Write heap dumps to the root of the volume above.
         - INNER_JAVA_OPTS=-Dwres.attemptToMigrate=false -XX:HeapDumpPath=/mnt/wres_share
        # Worker JVM should have 32m heap, wres should have 2310m heap
        mem_limit: 2730m
