version: '2.2'
services:
    tasker:
        ports:
         - "443:8443"
        image: "${DOCKER_REGISTRY}/wres/wres-tasker:20190924-ec45a2d"
        restart: always
        depends_on:
         - "broker"
        volumes:
         # For certificates and keys that correspond to them:
         - /mnt/wres_secrets:/wres_secrets:ro
         # To read output data:
         - /mnt/wres_share:/mnt/wres_share
        environment:
         # Make sure to pass through WRES_ENV_SUFFIX to tasker at runtime
         - JAVA_OPTS=-Dwres.broker=broker -Dwres.environment=${WRES_ENV_SUFFIX} -XX:HeapDumpPath=/mnt/wres_share/ -XX:OnOutOfMemoryError='mv /mnt/wres_share/java_pid%p.hprof /mnt/wres_share/java_pid%p_`hostname`.hprof; chmod 775 /mnt/wres_share/java_pid%p_`hostname`.hprof'
        # Tasker JVM should have 1305m max heap specified at launch
        # The total limit includes stack space which depends on Thread count
        mem_limit: 1880m
    broker:
        ports:
         - "5671:5671"
         - "15671:15671"
        image: "${DOCKER_REGISTRY}/wres/wres-broker:20190924-ec45a2d"
        restart: always
        volumes:
         # For certificates and keys that correspond to them:
         - /mnt/wres_secrets:/wres_secrets:ro
        environment:
         - RABBITMQ_CONFIG_FILE=rabbitmq${WRES_ENV_SUFFIX}.config
        # rabbitmq.conf should have 360m specified as high watermark
        mem_limit: 720m
    worker:
        image: "${DOCKER_REGISTRY}/wres/wres-worker:20190925-56b4740"
        restart: always
        depends_on:
         - "broker"
        volumes:
         # For input and output data:
         - /mnt/wres_share:/mnt/wres_share
         # For certificates, keys that correspond to them, and .pgpass:
         - /mnt/wres_secrets:/wres_secrets:ro
         # For input data:
         - /home:/home:ro
         # For logs (inside container, avoid writing to read-only /home)
         - /container_home
        environment:
         - JAVA_OPTS=-Dwres.broker=broker -Djava.io.tmpdir=/mnt/wres_share/evaluations -XX:HeapDumpPath=/mnt/wres_share/ -XX:OnOutOfMemoryError='mv /mnt/wres_share/java_pid%p.hprof /mnt/wres_share/java_pid%p_`hostname`.hprof; chmod 775 /mnt/wres_share/java_pid%p_`hostname`.hprof'
         - PGPASSFILE=/wres_secrets/.pgpass
         # Use caller-specified db hostname from env var WRES_DB_FQDN.
         # Do not auto-liquibase-migrate on each evaluation. This requires an
         # administrator to run the migration(s) during or after deployment.
         # Write heap dumps to the root of the volume above.
         - INNER_JAVA_OPTS=-Dwres.url=${WRES_DB_FQDN} -Dwres.databaseName=wres8 -Dwres.username=wres_user8 -Dwres.attemptToMigrate=false -XX:HeapDumpPath=/mnt/wres_share/ -XX:OnOutOfMemoryError='mv /mnt/wres_share/java_pid%p.hprof /mnt/wres_share/java_pid%p_`hostname`.hprof; chmod 775 /mnt/wres_share/java_pid%p_`hostname`.hprof'
        # Shim JVM should have 32m max heap, core JVM should have 2180m max heap
        mem_limit: 2600m
