version: '2.2'
services:
    tasker:
        ports:
         - "443:8443"
        image: "802f75eb7478"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_secrets:/wres_secrets:ro
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
         # Make sure to pass through WRES_ENV_SUFFIX to tasker at runtime
         - WRES_ENV_SUFFIX=${WRES_ENV_SUFFIX}
        # Tasker JVM should have 160m max heap specified at launch
        mem_limit: 360m
    broker:
        ports:
         - "5671:5671"
         - "15671:15671"
        image: "5175de99ac77"
        restart: always
        volumes:
         - /mnt/wres_secrets:/wres_secrets:ro
        environment:
         - RABBITMQ_CONFIG_FILE=rabbitmq${WRES_ENV_SUFFIX}.conf
        # rabbitmq.conf should have 180m specified as high watermark
        mem_limit: 360m
    worker:
        image: "3f775ea654f6"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_share:/mnt/wres_share
         - /mnt/wres_secrets:/wres_secrets:ro
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
         - PGPASSFILE=/wres_secrets/.pgpass
         #- INNER_JAVA_OPTS=-Dwres.logLevel=trace
        # Worker JVM should have 32m heap, wres should have 1628m heap
        mem_limit: 2048m
