version: '3'
services:
    tasker:
        ports:
         - "8585:8585"
        image: "b1e45dc08b14"
        restart: always
        depends_on:
         - "broker"
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
    broker:
        ports:
         - "4369:4369"
         - "5671:5671"
         - "5672:5672"
         - "25672:25672"
        image: "rabbitmq:3.7.4-alpine"
        restart: always
    worker:
        image: "a7acb88c1a61"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_share:/wres_data
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
