version: '2.2'
services:
    worker:
        image: "${DOCKER_REGISTRY}/wres/wres-worker:20190626-e953480"
        restart: always
        volumes:
         - /mnt/wres_share:/mnt/wres_share
         - /mnt/wres_secrets:/wres_secrets:ro
        network_mode: "host"
        environment:
         - JAVA_OPTS=-Dwres.broker=***REMOVED***wres-broker${WRES_ENV_SUFFIX} -Djava.io.tmpdir=/mnt/wres_share/evaluations
         - PGPASSFILE=/wres_secrets/.pgpass
        # Worker JVM should have 32m max heap, WRES should have 2310m max heap
        mem_limit: 2730m
