version: '3'
services:
    tasker:
        ports:
         - "8585:8585"
        image: "032c30588ef5"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_secrets:/wres_secrets
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
    broker:
        ports:
         - "5671:5671"
         - "15671:15671"
        image: "d878bdf609c1"
        restart: always
        volumes:
         - /mnt/wres_secrets:/wres_secrets
    worker:
        image: "75a2dfbab302"
        restart: always
        depends_on:
         - "broker"
        volumes:
         - /mnt/wres_share:/wres_data
         - /mnt/wres_secrets:/wres_secrets
        environment:
         - JAVA_OPTS=-Dwres.broker=broker
