#!/bin/bash

if [ $# -eq 0 ]; then
    echo 'usage: ./BuildDatabase <IOEP Database username> <host> <database name>'
else
    echo 'Droping old tables and data...'
    psql -U $1 -d $3 -h $2 -f DropTables.sql >/dev/null

    echo ''
    echo 'Adding wres.MeasurementUnit...'
    psql -U $1 -d $3 -h $2 -f wres.MeasurementUnit.sql >/dev/null

    echo ''
    echo 'Adding wres.Variable...'
    psql -U $1 -d $3 -h $2 -f wres.Variable.sql >/dev/null

    echo ''
    echo 'Adding wres.ForecastType...'
    psql -U $1 -d $3 -h $2 -f wres.ForecastType.sql >/dev/null

    echo ''
    echo 'Adding wres.Source...'
    psql -U $1 -d $3 -h $2 -f wres.Source.sql >/dev/null

    echo ''
    echo 'Adding wres.Forecast...'
    psql -U $1 -d $3 -h $2 -f wres.Forecast.sql >/dev/null

    echo ''
    echo 'Adding wres.VariablePosition...'
    psql -U $1 -d $3 -h $2 -f wres.VariablePosition.sql >/dev/null

    echo ''
    echo 'Adding wres.Ensemble...'
    psql -U $1 -d $3 -h $2 -f wres.Ensemble.sql >/dev/null

    echo ''
    echo 'Adding wres.ForecastEnsemble...'
    psql -U $1 -d $3 -h $2 -f wres.ForecastEnsemble.sql >/dev/null

    echo ''
    echo 'Adding wres.Observation...'
    psql -U $1 -d $3 -h $2 -f wres.Observation.sql >/dev/null

    echo ''
    echo 'Adding wres.UnitConversion.sql...'
    psql -U $1 -d $3 -h $2 -f wres.UnitConversion.sql >/dev/null

    echo ''
    echo 'Adding wres.Feature...'
    psql -U $1 -d $3 -h $2 -f wres.Feature.sql >/dev/null

    echo ''
    echo 'Adding wres.FeaturePosition...'
    psql -U $1 -d $3 -h $2 -f wres.FeaturePosition.sql >/dev/null

    echo ''
    echo 'Adding wres.ForecastValue...'
    psql -U $1 -d $3 -h $2 -f wres.ForecastValue.sql >/dev/null

    echo ''
    echo 'Adding get_variableposition_id function...'
    psql -U $1 -d $3 -h $2 -f get_variableposition_id.sql >/dev/null

    echo ''
    echo 'The wres schema has been sucessfully added.'
    echo ''
    
    echo 'Adding tables to the public schema...'

    echo ''
    echo 'Adding the ObservationLocation table...'
    psql -U $1 -d $3 -h $2 -f ObservationLocation.sql >/dev/null

    echo ''
    echo 'Loading location data...'
    psql -U $1 -d $3 -h $2 -f location_backup.sql >/dev/null

    echo ''
    echo 'Copying location data into ObservationLocation...'
    psql -U $1 -d $3 -h $2 -f copy_to_observationlocation.sql >/dev/null

    echo ''
    echo 'Adding the MeasurementUnit table...'
    psql -U $1 -d $3 -h $2 -f MeasurementUnit.sql >/dev/null

    echo ''
    echo 'Adding the Coordinate table...'
    psql -U $1 -d $3 -h $2 -f Coordinate.sql >/dev/null

    echo ''
    echo 'Adding the Projection table...'
    psql -U $1 -d $3 -h $2 -f Projection.sql >/dev/null

    echo ''
    echo 'Adding the Variable table...'
    psql -U $1 -d $3 -h $2 -f Variable.sql >/dev/null

    echo ''
    echo 'Adding the ForecastRange table...'
    psql -U $1 -d $3 -h $2 -f ForecastRange.sql >/dev/null

    echo ''
    echo 'Adding the Observation table...'
    psql -U $1 -d $3 -h $2 -f Observation.sql >/dev/null

    echo ''
    echo 'Adding the ObservationResult table...'
    psql -U $1 -d $3 -h $2 -f ObservationResult.sql >/dev/null

    echo ''
    echo 'Adding the Forecast table...'
    psql -U $1 -d $3 -h $2 -f Forecast.sql >/dev/null

    echo ''
    echo 'Adding the ForecastResult table...'
    psql -U $1 -d $3 -h $2 -f ForecastResult.sql >/dev/null

    echo ''
    echo 'Adding the USGSLocationCoordinate table...'
    psql -U $1 -d $3 -h $2 -f USGSLocationCoordinate.sql >/dev/null

    echo ''
    echo 'Adding the NWSLocationCoordinate table...'
    psql -U $1 -d $3 -h $2 -f NWSLocationCoordinate.sql >/dev/null

    echo ''
    echo 'Adding the UnitConversion table...'
    psql -U $1 -d $3 -h $2 -f UnitConversion.sql >/dev/null

    echo ''
    echo 'Adding the Forecast Coordinate table...'
    psql -U $1 -d $3 -h $2 -f ForecastCoordinate.sql >/dev/null

    echo ''
    echo 'Adding the ObservationCoordinate table...'
    psql -U $1 -d $3 -h $2 -f ObservationCoordinate.sql >/dev/null

    echo ''
    echo 'Inserting Coordinates for stations...'
    psql -U $1 -d $3 -h $2 -f InsertStationCoordinates.sql >/dev/null

    echo ''
    echo 'Transferring Locations from the public schema to the WRES schema...'
    psql -U $1 -d $3 -h $2 -f TransferLocationsToWRES.sql >/dev/null
fi
