package wres.events;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.function.Consumer;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import net.jcip.annotations.Immutable;
import wres.statistics.generated.EvaluationStatus;
import wres.statistics.generated.Pairs;
import wres.statistics.generated.Statistics;
import wres.statistics.generated.Consumer.Format;
import wres.statistics.generated.Evaluation;

/**
 * Bag of consumers to consume the messages associated with one evaluation. External subscribers are not represented 
 * here, as they are negotiated between the core client and one or more subscriber clients at runtime.
 * 
 * @author james.brown@hydrosolved.com
 */

@Immutable
public class Consumers
{

    private static final Logger LOGGER = LoggerFactory.getLogger( Consumers.class );

    /**
     * Consumers of evaluation events, which contain descriptions of evaluations to conduct.
     */

    private final List<Consumer<Evaluation>> evaluationConsumers;

    /**
     * Consumers of evaluation status events, which contain information about the status of an evaluation and 
     * associated user-facing messages (as distinct from developer-facing, which are logged).
     */

    private final List<Consumer<EvaluationStatus>> statusConsumers;

    /**
     * Consumers of evaluation statistics.
     */

    private final List<Consumer<Statistics>> statisticsConsumers;

    /**
     * The union of all output format types that are generated by the statistics consumers. If any types that are 
     * required by an evaluation are missing, then these must be delivered by one or more external subscribers.
     */

    private final Set<Format> statisticsConsumerTypes;

    /**
     * Consumers of groups of evaluation statistics where consumption is triggered by group.
     */

    private final List<Consumer<Collection<Statistics>>> groupedStatisticsConsumers;

    /**
     * Consumers of pairs.
     */

    private final List<Consumer<Pairs>> pairsConsumers;

    /**
     * @return the evaluation consumers
     */
    List<Consumer<Evaluation>> getEvaluationConsumers()
    {
        return this.evaluationConsumers; //Immutable on construction
    }

    /**
     * @return the evaluation status consumers
     */
    List<Consumer<EvaluationStatus>> getEvaluationStatusConsumers()
    {
        return this.statusConsumers; //Immutable on construction
    }

    /**
     * @return the statistics consumers
     */
    List<Consumer<Statistics>> getStatisticsConsumers()
    {
        return this.statisticsConsumers; //Immutable on construction
    }

    /**
     * @return the consumers of statistics groups
     */
    List<Consumer<Collection<Statistics>>> getGroupedStatisticsConsumers()
    {
        return this.groupedStatisticsConsumers; //Immutable on construction
    }

    /**
     * @return the consumers of pairs
     */
    List<Consumer<Pairs>> getPairsConsumers()
    {
        return this.pairsConsumers; //Immutable on construction
    }

    /**
     * @return the format types negotiated by statistics consumers
     */
    Set<Format> getStatisticsConsumerTypes()
    {
        return this.statisticsConsumerTypes; //Immutable on construction
    }

    /**
     * Builder.
     */

    public static class Builder
    {

        /**
         * Consumers of evaluation events, which contain descriptions of evaluations to conduct.
         */

        private List<Consumer<Evaluation>> evaluationConsumers = new ArrayList<>();

        /**
         * Consumers of evaluation status events, which contain information about the status of an evaluation and 
         * associated user-facing messages (as distinct from developer-facing, which are logged).
         */

        private List<Consumer<EvaluationStatus>> statusConsumers = new ArrayList<>();

        /**
         * Consumers of evaluation statistics.
         */

        private List<Consumer<Statistics>> statisticsConsumers = new ArrayList<>();

        /**
         * Union of format types handled by the statistics consumers.
         */

        private Set<Format> statisticsConsumerTypes = new HashSet<>();

        /**
         * Consumers of groups of evaluation statistics.
         */

        private List<Consumer<Collection<Statistics>>> groupedStatisticsConsumers = new ArrayList<>();

        /**
         * Consumers of pairs.
         */

        private List<Consumer<Pairs>> pairsConsumers = new ArrayList<>();

        /**
         * @param evaluationConsumer the evaluation consumer to add
         * @return this builder
         * @throws NullPointerException if the input is null
         */

        public Builder addEvaluationConsumer( Consumer<Evaluation> evaluationConsumer )
        {
            Objects.requireNonNull( evaluationConsumer );

            this.evaluationConsumers.add( evaluationConsumer );

            return this;
        }

        /**
         * @param statusConsumer the status consumer to add
         * @return this builder
         * @throws NullPointerException if the input is null
         */

        public Builder addStatusConsumer( Consumer<EvaluationStatus> statusConsumer )
        {
            Objects.requireNonNull( statusConsumer );

            this.statusConsumers.add( statusConsumer );

            return this;
        }

        /**
         * @param statisticsConsumer the statistics consumer to add
         * @param format one or more format types negotiated by the consumer
         * @return this builder
         * @throws NullPointerException if the consumer is null
         * @throws IllegalArgumentException if there are zero formats
         */

        public Builder addStatisticsConsumer( Consumer<Statistics> statisticsConsumer, Format... format )
        {
            Objects.requireNonNull( statisticsConsumer );

            if ( format.length == 0 )
            {
                throw new IllegalArgumentException( "Specify one or more format types handled by the consumer." );
            }

            this.statisticsConsumers.add( statisticsConsumer );
            this.statisticsConsumerTypes.addAll( Arrays.asList( format ) );

            return this;
        }

        /**
         * @param groupStatisticsConsumer the consumer for groups of evaluation events
         * @param format one or more format types negotiated by the consumer
         * @return this builder
         * @throws NullPointerException if the input is null
         * @throws IllegalArgumentException if there are zero formats
         */

        public Builder addGroupedStatisticsConsumer( Consumer<Collection<Statistics>> groupStatisticsConsumer,
                                                     Format... format )
        {
            Objects.requireNonNull( groupStatisticsConsumer );

            if ( format.length == 0 )
            {
                throw new IllegalArgumentException( "Specify one or more format types handled by the consumer." );
            }

            this.groupedStatisticsConsumers.add( groupStatisticsConsumer );
            this.statisticsConsumerTypes.addAll( Arrays.asList( format ) );

            return this;
        }

        /**
         * @param pairsConsumer the pairs consumer to add
         * @return this builder
         */

        public Builder addPairsConsumer( Consumer<Pairs> pairsConsumer )
        {
            if ( Objects.nonNull( pairsConsumer ) )
            {
                this.pairsConsumers.add( pairsConsumer );
            }

            return this;
        }

        /**
         * Builds a consumer group.
         * 
         * @return a consumer group
         */

        public Consumers build()
        {
            return new Consumers( this );
        }
    }

    /**
     * Hidden constructor.
     * 
     * @param builder the builder
     */
    private Consumers( Builder builder )
    {
        this.evaluationConsumers = Collections.unmodifiableList( builder.evaluationConsumers );
        this.statisticsConsumers = Collections.unmodifiableList( builder.statisticsConsumers );
        this.statusConsumers = Collections.unmodifiableList( builder.statusConsumers );
        this.groupedStatisticsConsumers = Collections.unmodifiableList( builder.groupedStatisticsConsumers );
        this.pairsConsumers = Collections.unmodifiableList( builder.pairsConsumers );
        this.statisticsConsumerTypes = Collections.unmodifiableSet( builder.statisticsConsumerTypes );

        LOGGER.debug( "Successfully constructed a consumer group with {} evaluation consumers, {} evaluation status "
                      + "consumers, {} statistics consumers, {} and pairs consumers. The statistics consumers "
                      + "negotiate the format types {}.",
                      this.getEvaluationConsumers().size(),
                      this.getEvaluationStatusConsumers().size(),
                      this.getStatisticsConsumers().size(),
                      this.getPairsConsumers().size(),
                      this.getStatisticsConsumerTypes() );
    }

}
