#!/bin/bash

if [ $# -eq 0 ]; then
    echo 'usage: ./Monitor <Database username> [<host> <database name>]'
else
    database=${3:-"wres"}
    host=${2:-"***REMOVED***eds-dev1.***REMOVED***.***REMOVED***"}
    while true; do
        psql -U $1 -d $database -h $host -f TrackRequests.sql
        sleep 2
    done
fi
